# Generated by Django 3.2 on 2021-04-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
